### ISSUE TITLE
What dependencies to set when using SBT

### ISSUE THREAD

**Issue by DandyDev** [kite-sdk/kite#301]
I'm trying to build a Scala app that uses KiteSDK to put some data in HDFS. I'm using SBT as my build tool, so I can't use a parent POM. I'm running into problems getting the right dependencies in, which leads to this error when trying to build a `DatasetDescriptor`:

```scala
scala> val descriptor = new DatasetDescriptor.Builder().schema(accountSchema).build()
warning: Class org.apache.hadoop.fs.Path not found - continuing with a stub.
java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
  ... 43 elided
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
  at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 43 more
```

My sbt file:

```scala
name := "myapp"

organization := "com.datadudes"

version := "0.1-SNAPSHOT"

scalaVersion := "2.11.4"

libraryDependencies ++= Seq(
  "org.scala-lang.modules"    %% "scala-xml"        % "1.0.2",
  "org.apache.avro"           % "avro"              % "1.7.5",
  "com.force.api"             % "force-wsc"         % "33.0.1" exclude("org.antlr", "ST4"),
  "com.force.api"             % "force-partner-api" % "33.0.1",
  "com.datadudes"             %% "wsdl2avro"        % "0.1-SNAPSHOT",
  "org.kitesdk"               % "kite-data-core"    % "0.17.1",
  "org.specs2"                %% "specs2-junit"     % "2.4.15"    % "test"
)
```

What other dependencies do I need, next to `kite-data-core` in order to be able to use Kite Datasets?

**Comment by rdblue** [comment]
On 02/04/2015 04:39 AM, Daan Debie wrote:
> I'm trying to build a Scala app that uses KiteSDK to put some data in
> HDFS. I'm using SBT as my build tool, so I can't use a parent POM. I'm
> running into problems getting the right dependencies in, which leads to
> this error when trying to build a |DatasetDescriptor|:
>
> scala>  val  descriptor  =  new  DatasetDescriptor.Builder().schema(accountSchema).build()
> warning:  Class  org.apache.hadoop.fs.Path  not found-  continuingwith  a  stub.
> java.lang.NoClassDefFoundError:  org/apache/hadoop/fs/FSDataInputStream
>    ...43  elided
> Caused  by: java.lang.ClassNotFoundException:  org.apache.hadoop.fs.FSDataInputStream
>    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
>    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
>    at java.security.AccessController.doPrivileged(Native  Method)
>    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
>    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>    ...43  more

Kite needs org.apache.hadoop:hadoop-client, which depends on hadoop-hdfs 
and hadoop-common for these classes.

But because Kite is compatible with several different versions of 
Hadoop, we mark these as provided dependencies so sbt probably won't 
pull them in as transitive dependencies. I think all you need to do is 
to add the artifacts from our Hadoop dependency aggregator POMs, 
depending on your version:

default: 
https://github.com/kite-sdk/kite/blob/master/kite-hadoop-dependencies/default/pom.xml

CDH5: 
https://github.com/kite-sdk/kite/blob/master/kite-hadoop-dependencies/cdh5/pom.xml

rb



-- 
Ryan Blue
Software Engineer
Cloudera, Inc.

**Comment by DandyDev** [comment]
That did it for me! For future reference, if anyone else tries to use SBT to create a standalone Scala app that uses KiteSDK, this build config worked for me:

```scala
name := "myapp"

organization := "com.datadudes"

version := "0.1-SNAPSHOT"

scalaVersion := "2.11.4"

resolvers += "Cloudera Repositories" at "https://repository.cloudera.com/artifactory/cloudera-repos"

libraryDependencies ++= Seq(
  "org.scala-lang.modules"    %% "scala-xml"        % "1.0.2",
  "org.apache.avro"           % "avro"              % "1.7.5",
  "com.force.api"             % "force-wsc"         % "33.0.1" exclude("org.antlr", "ST4"),
  "com.force.api"             % "force-partner-api" % "33.0.1",
  "com.datadudes"             %% "wsdl2avro"        % "0.1-SNAPSHOT",
  "org.kitesdk"                % "kite-hadoop-cdh5-dependencies" % "0.17.1" pomOnly(),
  "org.kitesdk"               % "kite-data-core"    % "0.17.1",
  "org.specs2"                %% "specs2-junit"     % "2.4.15"    % "test"
)
```

Important changes: adding the Cloudera repo as resolver, and adding the `kite-hadoop-cdh5-dependencies` artifact as dependency.

Thanks for the help!

**Comment by rdblue** [comment]
Thanks for posting your final solution, @DandyDev!
