### ISSUE TITLE
extractAvroPaths does not traverses arrays with the '[]' notation when array is part of a union

### ISSUE THREAD

**Issue by SOLID-Design** [kite-sdk/kite#435]
When avro schema contains an array within a union then the '[]' operator does not traverses the array. 

Given schema:
`{ "namespace": "org.kitesdk.morphline.avro",
    "type": "record",
    "name": "ArrayInUnionTestRecord",
    "fields": [
          {"name": "items", "type": {"type": "array", "items": "string"}},
          {"name": "itemsInUnion", "type": ["null", {"type": "array", "items":"string"}], "default": null}
     ]
  }`

and configuration
`extractAvroPaths {
       paths : {
            "/items[]" : "/items[]"
            "/itemsInUnion[]" : "/itemsInUnion[]"
       }
 }`

_/items[]_ is properly extracted but _/itemsInUnion[]_ is not.

**Comment by whoschek** [comment]
Thanks for the contribution! I committed a fix that pinpoints the issue a bit more precisely, here: https://github.com/kite-sdk/kite/commit/50781c4ddca9763304119185d6caf86f6b1f6ef1
