### ISSUE TITLE
Reporting a security issue

### ISSUE THREAD

**Issue by artem-smotrakov** [kite-sdk/kite#507]
I have one security-related question about Kite. I am not sure whether it's going to be considered as a vulnerability or a security enhancement - it depends on how one looks at it. Before opening an issue, I'd like to share it privately with the project maintainers. Who would be the best contact? Unfortunately, I didn't find any contact for that. In fact, the project doesn't look active anymore.

@szvasas @whoschek @ebogi (found you in the commit history)

**Comment by tmgstevens** [comment]
Hi @artem-smotrakov - please can you email to security@cloudera.com
https://www.cloudera.com/contact-us/security.html

**Comment by artem-smotrakov** [comment]
Hi @tmgstevens I did a year ago. This one can be closed, I think.
